import type { Station, StationColors, StationVisualizerConfig, StreamQuality, StationStatus } from '@/types'

const STATIONS_CONFIG: Station[] = [
  {
    id: 'pump-radio',
    slug: 'pump-radio',
    name: 'Pump! Radio',
    tagline: 'Hardtechno · Hardcore · Nu Jazz',
    genre: 'Multi-género Underground',
    description: 'La nave nodriza. Hardtechno industrial para el workout, hardcore gabber para el caos, Nu Jazz para el after. Argentina al mundo.',
    colors: {
      primary: '#ff2200',
      secondary: '#cc0000',
      accent: '#ff6600',
      glow: '#ff3300',
      background: 'radial-gradient(ellipse at center, #1a0a0a 0%, #0a0505 70%)',
    },
    status: 'LIVE',
    streamUrl: 'https://stream.zeno.fm/gpv2kgzwum0uv',
    metadataUrl: 'https://api.zeno.fm/mounts/metadata/subscribe/e4vzegzwum0uv',
    quality: 'HIGH',
    bpm: 155,
    tags: ['hardtechno', 'hardcore', 'gabber', 'nujazz', 'industrial'],
    logoUrl: null,
    backgroundUrl: null,
    sortOrder: 0,
    isActive: true,
    visualizer: {
      type: 'industrial',
      particleColor: '#ff2200',
      spectrumStyle: 'sharp',
      backgroundShader: 'grid-pulse',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'neon-hardstyle',
    slug: 'neon-hardstyle',
    name: 'Neon Hardstyle',
    tagline: 'Raw · Melodic · Euphoric',
    genre: 'Hardstyle',
    description: 'Kicks que rompen el suelo. Reverse bass, melodías épicas, euphoria pura. De Headhunterz a los nuevos talentos del rawstyle.',
    colors: {
      primary: '#00ddff',
      secondary: '#0099cc',
      accent: '#66ffff',
      glow: '#00ccff',
      background: 'radial-gradient(ellipse at center, #0a1a1f 0%, #050a0d 70%)',
    },
    status: 'COMING_SOON',
    streamUrl: 'https://stream.example.com/hardstyle',
    metadataUrl: 'https://api.example.com/metadata/hardstyle',
    quality: 'HIGH',
    bpm: 150,
    tags: ['hardstyle', 'rawstyle', 'euphoric', 'melodic', 'reverse-bass'],
    logoUrl: null,
    backgroundUrl: null,
    sortOrder: 1,
    isActive: true,
    visualizer: {
      type: 'euphoric',
      particleColor: '#00ddff',
      spectrumStyle: 'smooth',
      backgroundShader: 'wave-field',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'neo-jazz',
    slug: 'neo-jazz',
    name: 'Neo Jazz',
    tagline: 'Nu Jazz · Future Jazz · Jazztronica',
    genre: 'Nu Jazz / Future Jazz',
    description: 'Jazz del futuro. Robert Glasper, Flying Lotus, Thundercat, BADBADNOTGOOD. Beats rotos, sintes vintage, grooves para producir o flotar.',
    colors: {
      primary: '#4488aa',
      secondary: '#226688',
      accent: '#66bbdd',
      glow: '#55aaff',
      background: 'radial-gradient(ellipse at center, #0a1218 0%, #05080c 70%)',
    },
    status: 'COMING_SOON',
    streamUrl: 'https://stream.example.com/nujazz',
    metadataUrl: 'https://api.example.com/metadata/nujazz',
    quality: 'STANDARD',
    bpm: 95,
    tags: ['nujazz', 'futurejazz', 'jazztronica', 'downtempo', 'beats'],
    logoUrl: null,
    backgroundUrl: null,
    sortOrder: 2,
    isActive: true,
    visualizer: {
      type: 'organic',
      particleColor: '#4488aa',
      spectrumStyle: 'flowing',
      backgroundShader: 'liquid-metal',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'electric-grooves',
    slug: 'electric-grooves',
    name: 'Electric Grooves',
    tagline: 'Jazztronica · Broken Beats · Vinyl Vibes',
    genre: 'Jazztronica / Electronic',
    description: 'La intersección orgánica. Kaytranada, Knxwledge, Sam Gendel. Samples de vinilo, sintes analógicos, ritmos que no encajan en géneros.',
    colors: {
      primary: '#668855',
      secondary: '#446633',
      accent: '#88bb66',
      glow: '#77aa55',
      background: 'radial-gradient(ellipse at center, #0a120a 0%, #050805 70%)',
    },
    status: 'COMING_SOON',
    streamUrl: 'https://stream.example.com/jazztronica',
    metadataUrl: 'https://api.example.com/metadata/jazztronica',
    quality: 'STANDARD',
    bpm: 110,
    tags: ['jazztronica', 'beats', 'vinyl', 'experimental', 'lofi'],
    logoUrl: null,
    backgroundUrl: null,
    sortOrder: 3,
    isActive: true,
    visualizer: {
      type: 'vinyl',
      particleColor: '#668855',
      spectrumStyle: 'groove',
      backgroundShader: 'vinyl-grooves',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'core-frequency',
    slug: 'core-frequency',
    name: 'Core Frequency',
    tagline: 'Hardcore · Uptempo · Terror · Gabber',
    genre: 'Hardcore',
    description: '180+ BPM sin piedad. Uptempo, Frenchcore, Terror, Early Gabber. Cuando el kick tiene que doler.',
    colors: {
      primary: '#dd2244',
      secondary: '#aa0033',
      accent: '#ff5577',
      glow: '#ff3366',
      background: 'radial-gradient(ellipse at center, #1a0508 0%, #0a0203 70%)',
    },
    status: 'COMING_SOON',
    streamUrl: 'https://stream.example.com/hardcore',
    metadataUrl: 'https://api.example.com/metadata/hardcore',
    quality: 'HIGH',
    bpm: 180,
    tags: ['hardcore', 'uptempo', 'frenchcore', 'terror', 'gabber'],
    logoUrl: null,
    backgroundUrl: null,
    sortOrder: 4,
    isActive: true,
    visualizer: {
      type: 'aggressive',
      particleColor: '#dd2244',
      spectrumStyle: 'brutal',
      backgroundShader: 'glitch-grid',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'black-tunnel',
    slug: 'black-tunnel',
    name: 'Black Tunnel Radio',
    tagline: 'Dark Techno · Industrial · EBM',
    genre: 'Dark Techno / Industrial',
    description: 'El túnel sin luz. Berghain sound, industrial puro, EBM clásico, dark techno hipnótico. Para las 4am.',
    colors: {
      primary: '#222233',
      secondary: '#111122',
      accent: '#444466',
      glow: '#333355',
      background: 'radial-gradient(ellipse at center, #050508 0%, #000000 60%)',
    },
    status: 'COMING_SOON',
    streamUrl: 'https://stream.example.com/darktechno',
    metadataUrl: 'https://api.example.com/metadata/darktechno',
    quality: 'STANDARD',
    bpm: 128,
    tags: ['darktechno', 'industrial', 'ebm', 'minimal', 'hypnotic'],
    logoUrl: null,
    backgroundUrl: null,
    sortOrder: 5,
    isActive: true,
    visualizer: {
      type: 'minimal',
      particleColor: '#444466',
      spectrumStyle: 'subtle',
      backgroundShader: 'void',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const STATIONS = STATIONS_CONFIG
export const DEFAULT_STATION = 'pump-radio'
export const STATIONS_BY_SLUG = Object.fromEntries(STATIONS_CONFIG.map(s => [s.slug, s]))
export const LIVE_STATIONS = STATIONS_CONFIG.filter(s => s.status === 'LIVE' && s.isActive)
export const ACTIVE_STATIONS = STATIONS_CONFIG.filter(s => s.isActive).sort((a, b) => a.sortOrder - b.sortOrder)